# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8eea7c57c79c48c12d460a149b7aed4cb86fc60c875e3534e91305c1684213cd6d78ef04d2585c0d9a0d94efc234f6de3d2a5634e9fb71c70811a69a2ae29857

test:
  secret_key_base: a392ef1ce2de28a4409e4b0b0a762f249d793787bc732e12ed6cd2c23501948547abf5bb0242558e8fc49a9e3c81e4fac6cbf0e8f794a9e0e9ebb1a061ee997f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
